### ISSUE TITLE
Debugging these alerts...

### ISSUE THREAD

**Issue by nomad5am** [grimmolf/LemonTrading#1] opened 2020-03-06 03:22 UTC
First of all, this is some great stuff you are doing! Thank you for publishing this!

 I'm digging in the code for hours for but I just don't see why the alerts won't trigger. The source for entry and exit is defined as close - not sure if that is such a good idea especially for exits. 

Any ideas?

**Comment by grimmolf** [comment] 2020-03-06 05:06
Thanks for the input and taking a look at the code as well! I think I
figured out the alert issue. Line 209 (now line 210) contained a condition
"barstate.isrealtime", which it turns out causes a redraw of the chart, and
I think the redraw function was occurring during the period where the alert
would normally fire. After commending it out and replacing the line with
the new one on 211, I'm able to get alerts firing appropriately.

As for the entry being based on close, that's alright with me, as I don't
consider the M or W confirmed until after a close beyond point C. I'll take
a look at the exit condition, which should just be based on any movement
beyond the level.

Again, thanks for contributing!!!

**Comment by nomad5am** [comment] 2020-03-06 07:08
Oh wow - well it makes sense but I wouldn't have noticed this one. Will do some forward testing now with the fix. 

And yes ofc I agree, entry should be on candle close - exits once per bar tho. I'll set it up and report back ;) 

Fantastic work buddy

**Comment by grimmolf** [comment] 2020-04-20 02:21
I'm going to go ahead and close this issue, but let me know if you see anything else that might need fixing.

**Closed** 2020-04-20 02:21 UTC
